//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace unvell.ReoGrid.Editor.LangRes {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("unvell.ReoGrid.Editor.LangRes.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alignment 的本地化字符串。
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degrees 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Degrees {
            get {
                return ResourceManager.GetString("AlignmentPage_Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Horizontal: 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Horizontal {
            get {
                return ResourceManager.GetString("AlignmentPage_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Indent: 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Indent {
            get {
                return ResourceManager.GetString("AlignmentPage_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orientation 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Orientation {
            get {
                return ResourceManager.GetString("AlignmentPage_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text alignment 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Text_Alignment {
            get {
                return ResourceManager.GetString("AlignmentPage_Text_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text control 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Text_Control {
            get {
                return ResourceManager.GetString("AlignmentPage_Text_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Vertical: 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Vertical {
            get {
                return ResourceManager.GetString("AlignmentPage_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Wrap text 的本地化字符串。
        /// </summary>
        internal static string AlignmentPage_Wrap_Text {
            get {
                return ResourceManager.GetString("AlignmentPage_Wrap_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Appearance Editor 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Caption {
            get {
                return ResourceManager.GetString("AppearanceEditor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export C# 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Export_CSharp {
            get {
                return ResourceManager.GetString("AppearanceEditor_Export_CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export VB.NET 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Export_VBNET {
            get {
                return ResourceManager.GetString("AppearanceEditor_Export_VBNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Highlight: 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Highlight {
            get {
                return ResourceManager.GetString("AppearanceEditor_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Main: 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Main {
            get {
                return ResourceManager.GetString("AppearanceEditor_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to &amp;Default 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Reset_To_Default {
            get {
                return ResourceManager.GetString("AppearanceEditor_Reset_To_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Border &amp;Width: 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Selection_Border_Width {
            get {
                return ResourceManager.GetString("AppearanceEditor_Selection_Border_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use &amp;System Highlight Color 的本地化字符串。
        /// </summary>
        internal static string AppearanceEditor_Use_System_Highligh_Color {
            get {
                return ResourceManager.GetString("AppearanceEditor_Use_System_Highligh_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border 的本地化字符串。
        /// </summary>
        internal static string Border {
            get {
                return ResourceManager.GetString("Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        internal static string BorderPage_Line {
            get {
                return ResourceManager.GetString("BorderPage_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Presets 的本地化字符串。
        /// </summary>
        internal static string BorderPage_Presets {
            get {
                return ResourceManager.GetString("BorderPage_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Style: 的本地化字符串。
        /// </summary>
        internal static string BorderPage_Style {
            get {
                return ResourceManager.GetString("BorderPage_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Cancel 的本地化字符串。
        /// </summary>
        internal static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close 的本地化字符串。
        /// </summary>
        internal static string Btn_Close {
            get {
                return ResourceManager.GetString("Btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delete 的本地化字符串。
        /// </summary>
        internal static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit 的本地化字符串。
        /// </summary>
        internal static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New 的本地化字符串。
        /// </summary>
        internal static string Btn_New {
            get {
                return ResourceManager.GetString("Btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body 的本地化字符串。
        /// </summary>
        internal static string CellBody {
            get {
                return ResourceManager.GetString("CellBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column 的本地化字符串。
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Merge 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Cell_Merge {
            get {
                return ResourceManager.GetString("CtxMenu_Cell_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Unmerge 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Cell_Unmerge {
            get {
                return ResourceManager.GetString("CtxMenu_Cell_Unmerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filter 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Col_Clear_Filter {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Clear_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column &amp;Width... 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Col_Column_Width {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Column_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delete Columns 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Col_Delete_Columns {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Delete_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Filter 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Col_Filter {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Insert Columns 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Col_Insert_Columns {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Insert_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Default Width 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Col_Reset_To_Default_Width {
            get {
                return ResourceManager.GetString("CtxMenu_Col_Reset_To_Default_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delete Rows 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Row_Delete_Rows {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Delete_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Insert Rows 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Row_Insert_Rows {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Insert_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Default Height 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Row_Reset_to_Default_Height {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Reset_to_Default_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row &amp;Height... 的本地化字符串。
        /// </summary>
        internal static string CtxMenu_Row_Row_Height {
            get {
                return ResourceManager.GetString("CtxMenu_Row_Row_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Format 的本地化字符串。
        /// </summary>
        internal static string Data_Format {
            get {
                return ResourceManager.GetString("Data_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTime 的本地化字符串。
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Name 的本地化字符串。
        /// </summary>
        internal static string DefineNamedRange_Caption {
            get {
                return ResourceManager.GetString("DefineNamedRange_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Comment: 的本地化字符串。
        /// </summary>
        internal static string DefineNamedRange_Comment {
            get {
                return ResourceManager.GetString("DefineNamedRange_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Name: 的本地化字符串。
        /// </summary>
        internal static string DefineNamedRange_Name {
            get {
                return ResourceManager.GetString("DefineNamedRange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Range: 的本地化字符串。
        /// </summary>
        internal static string DefineNamedRange_Range {
            get {
                return ResourceManager.GetString("DefineNamedRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill 的本地化字符串。
        /// </summary>
        internal static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Background Color: 的本地化字符串。
        /// </summary>
        internal static string FillPage_Background_Color {
            get {
                return ResourceManager.GetString("FillPage_Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill &amp;Pattern 的本地化字符串。
        /// </summary>
        internal static string FillPage_Fill_Pattern {
            get {
                return ResourceManager.GetString("FillPage_Fill_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill Pattern &amp;Color 的本地化字符串。
        /// </summary>
        internal static string FillPage_Fill_Pattern_Color {
            get {
                return ResourceManager.GetString("FillPage_Fill_Pattern_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill Pattern &amp;Style 的本地化字符串。
        /// </summary>
        internal static string FillPage_Fill_Pattern_Style {
            get {
                return ResourceManager.GetString("FillPage_Fill_Pattern_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV File(*.csv)|*.csv|Text file(*.txt)|*.txt|All files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string Filter_Export_As_CSV {
            get {
                return ResourceManager.GetString("Filter_Export_As_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Supported Files(*.xlsx;*.csv;*.rgf)|*.xlsx;*.csv;*.rgf|ReoGrid XML Format(*.rgf)|*.rgf|Excel 2007(*.xlsx)|*.xlsx|CSV File(*.csv)|*.csv|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string Filter_Load_File {
            get {
                return ResourceManager.GetString("Filter_Load_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel 2007(*.xlsx)|*.xlsx|ReoGrid XML Format(*.rgf)|*.rgf|CSV File(*.csv)|*.csv|All Files(*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string Filter_Save_File {
            get {
                return ResourceManager.GetString("Filter_Save_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Accounting Format 的本地化字符串。
        /// </summary>
        internal static string FormatPage_AccountingFormat {
            get {
                return ResourceManager.GetString("FormatPage_AccountingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Cells 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Caption {
            get {
                return ResourceManager.GetString("FormatPage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Category: 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Category {
            get {
                return ResourceManager.GetString("FormatPage_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Decimal Places: 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Decimal_Places {
            get {
                return ResourceManager.GetString("FormatPage_Decimal_Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Locale (location): 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Locale {
            get {
                return ResourceManager.GetString("FormatPage_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Negative numbers: 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Negative_Numbers {
            get {
                return ResourceManager.GetString("FormatPage_Negative_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Pattern: 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Pattern {
            get {
                return ResourceManager.GetString("FormatPage_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Symbol: 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Symbol {
            get {
                return ResourceManager.GetString("FormatPage_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Type: 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Type {
            get {
                return ResourceManager.GetString("FormatPage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Use 1000 Separator ({0}) 的本地化字符串。
        /// </summary>
        internal static string FormatPage_Use_1000_Separator {
            get {
                return ResourceManager.GetString("FormatPage_Use_1000_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formula 的本地化字符串。
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto &amp;fit to cell 的本地化字符串。
        /// </summary>
        internal static string HeaderProperty_Auto_Fit_To_Cell {
            get {
                return ResourceManager.GetString("HeaderProperty_Auto_Fit_To_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header Properties 的本地化字符串。
        /// </summary>
        internal static string HeaderProperty_Caption {
            get {
                return ResourceManager.GetString("HeaderProperty_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Column &amp;Type: 的本地化字符串。
        /// </summary>
        internal static string HeaderProperty_Default_Column_Type {
            get {
                return ResourceManager.GetString("HeaderProperty_Default_Column_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Panel &amp;Width: 的本地化字符串。
        /// </summary>
        internal static string HeaderProperty_Panel_Width {
            get {
                return ResourceManager.GetString("HeaderProperty_Panel_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Text: 的本地化字符串。
        /// </summary>
        internal static string HeaderProperty_Text {
            get {
                return ResourceManager.GetString("HeaderProperty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text &amp;Color: 的本地化字符串。
        /// </summary>
        internal static string HeaderProperty_Text_Color {
            get {
                return ResourceManager.GetString("HeaderProperty_Text_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        internal static string Horizontal_Alignment_Center {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distributed (Indent) 的本地化字符串。
        /// </summary>
        internal static string Horizontal_Alignment_Distributed {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Distributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string Horizontal_Alignment_General {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        internal static string Horizontal_Alignment_Left {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string Horizontal_Alignment_Right {
            get {
                return ResourceManager.GetString("Horizontal_Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://reogrid.net/ 的本地化字符串。
        /// </summary>
        internal static string HP_Homepage {
            get {
                return ResourceManager.GetString("HP_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://reogrid.net/document 的本地化字符串。
        /// </summary>
        internal static string HP_Homepage_Document {
            get {
                return ResourceManager.GetString("HP_Homepage_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 inch 的本地化字符串。
        /// </summary>
        internal static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Color: 的本地化字符串。
        /// </summary>
        internal static string Label_Color {
            get {
                return ResourceManager.GetString("Label_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landscape 的本地化字符串。
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Cells 的本地化字符串。
        /// </summary>
        internal static string Menu_Cells {
            get {
                return ResourceManager.GetString("Menu_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Merge Cells 的本地化字符串。
        /// </summary>
        internal static string Menu_Cells_Merge_Cells {
            get {
                return ResourceManager.GetString("Menu_Cells_Merge_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Unmerge Cells 的本地化字符串。
        /// </summary>
        internal static string Menu_Cells_Unmerge_Cells {
            get {
                return ResourceManager.GetString("Menu_Cells_Unmerge_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Cells &amp;Type 的本地化字符串。
        /// </summary>
        internal static string Menu_Change_Cells_Type {
            get {
                return ResourceManager.GetString("Menu_Change_Cells_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Copy 的本地化字符串。
        /// </summary>
        internal static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C&amp;ut 的本地化字符串。
        /// </summary>
        internal static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Clear {
            get {
                return ResourceManager.GetString("Menu_Edit_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Cell Style 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Focus_Cell_Style {
            get {
                return ResourceManager.GetString("Menu_Edit_Focus_Cell_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read-only 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Readonly {
            get {
                return ResourceManager.GetString("Menu_Edit_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat Last &amp;Action 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Repeat_Last_Action {
            get {
                return ResourceManager.GetString("Menu_Edit_Repeat_Last_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select &amp;All 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Select_All {
            get {
                return ResourceManager.GetString("Menu_Edit_Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Selection 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag To &amp;Fill Serial 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Drag_To_Fill_Serial {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Drag_To_Fill_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Drag To Move Content 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Drag_To_Move_Content {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Drag_To_Move_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection &amp;Mode 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Mode {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Mode_Cell {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Mode_Column {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Mode_None {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Range (Default) 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Mode_Range {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Mode_Row {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Mode_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Move Direction 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Move_Direction {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Move_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Down 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Move_Direction_Down {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Move_Direction_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Right (Default) 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Move_Direction_Right {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Move_Direction_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection S&amp;tyle 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Style {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Solid Rectangle 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Style_Default {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Focus Rectangle 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Style_Focus_Rect {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style_Focus_Rect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string Menu_Edit_Selection_Style_None {
            get {
                return ResourceManager.GetString("Menu_Edit_Selection_Style_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File 的本地化字符串。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit RGF &amp;XML... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Edit_RGF_XML {
            get {
                return ResourceManager.GetString("Menu_File_Edit_RGF_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Exit 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export As &amp;CSV... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Export_As_CSV {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Current Worksheet... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Export_As_CSV_Current_Worksheet {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_CSV_Current_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Selected Range... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Export_As_CSV_Selected_Range {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_CSV_Selected_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export As &amp;HTML... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Export_As_HTML {
            get {
                return ResourceManager.GetString("Menu_File_Export_As_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New 的本地化字符串。
        /// </summary>
        internal static string Menu_File_New {
            get {
                return ResourceManager.GetString("Menu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New &amp;Window... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_New_Window {
            get {
                return ResourceManager.GetString("Menu_File_New_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Open 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Print... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Print {
            get {
                return ResourceManager.GetString("Menu_File_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print P&amp;review... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Print_Preview {
            get {
                return ResourceManager.GetString("Menu_File_Print_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Se&amp;ttings... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Print_Settings {
            get {
                return ResourceManager.GetString("Menu_File_Print_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Save {
            get {
                return ResourceManager.GetString("Menu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save &amp;As... 的本地化字符串。
        /// </summary>
        internal static string Menu_File_Save_As {
            get {
                return ResourceManager.GetString("Menu_File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Format Cells... 的本地化字符串。
        /// </summary>
        internal static string Menu_Format_Cells {
            get {
                return ResourceManager.GetString("Menu_Format_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Formula 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula {
            get {
                return ResourceManager.GetString("Menu_Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Auto Function 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Auto_Function {
            get {
                return ResourceManager.GetString("Menu_Formula_Auto_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Define &amp;Name... 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Define_Name {
            get {
                return ResourceManager.GetString("Menu_Formula_Define_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name &amp;Manager... 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Name_Manager {
            get {
                return ResourceManager.GetString("Menu_Formula_Name_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recalculate Worksheet 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Recalculate_Worksheet {
            get {
                return ResourceManager.GetString("Menu_Formula_Recalculate_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Remove Trace Arrows 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Remove_Trace_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove All &amp;Arrows 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Remove_Trace_Arrows_Remove_All_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows_Remove_All_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove &amp;Dependent Arrows 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Remove_Trace_Arrows_Remove_Dependent_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows_Remove_Dependent_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove &amp;Precedent Arrows 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Remove_Trace_Arrows_Remove_Precedent_Arrows {
            get {
                return ResourceManager.GetString("Menu_Formula_Remove_Trace_Arrows_Remove_Precedent_Arrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Suspend Reference Updates 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Suspend_Reference_Updates {
            get {
                return ResourceManager.GetString("Menu_Formula_Suspend_Reference_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace &amp;Dependents 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Trace_Dependents {
            get {
                return ResourceManager.GetString("Menu_Formula_Trace_Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace &amp;Precedents 的本地化字符串。
        /// </summary>
        internal static string Menu_Formula_Trace_Precedents {
            get {
                return ResourceManager.GetString("Menu_Formula_Trace_Precedents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Group 的本地化字符串。
        /// </summary>
        internal static string Menu_Group {
            get {
                return ResourceManager.GetString("Menu_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Help 的本地化字符串。
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;About... 的本地化字符串。
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Documents... 的本地化字符串。
        /// </summary>
        internal static string Menu_Help_Documents {
            get {
                return ResourceManager.GetString("Menu_Help_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Homepage... 的本地化字符串。
        /// </summary>
        internal static string Menu_Help_Homepage {
            get {
                return ResourceManager.GetString("Menu_Help_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Hide 的本地化字符串。
        /// </summary>
        internal static string Menu_Hide {
            get {
                return ResourceManager.GetString("Menu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Page &amp;Break 的本地化字符串。
        /// </summary>
        internal static string Menu_Insert_Page_Break {
            get {
                return ResourceManager.GetString("Menu_Insert_Page_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More... 的本地化字符串。
        /// </summary>
        internal static string Menu_More {
            get {
                return ResourceManager.GetString("Menu_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Paste 的本地化字符串。
        /// </summary>
        internal static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Property... 的本地化字符串。
        /// </summary>
        internal static string Menu_Property {
            get {
                return ResourceManager.GetString("Menu_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Redo 的本地化字符串。
        /// </summary>
        internal static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Page Break 的本地化字符串。
        /// </summary>
        internal static string Menu_Remove_Page_Break {
            get {
                return ResourceManager.GetString("Menu_Remove_Page_Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset All Page &amp;Breaks 的本地化字符串。
        /// </summary>
        internal static string Menu_Reset_All_Page_Breaks {
            get {
                return ResourceManager.GetString("Menu_Reset_All_Page_Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sc&amp;ript 的本地化字符串。
        /// </summary>
        internal static string Menu_Script {
            get {
                return ResourceManager.GetString("Menu_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run &amp;Function... 的本地化字符串。
        /// </summary>
        internal static string Menu_Script_Run_Function {
            get {
                return ResourceManager.GetString("Menu_Script_Run_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script &amp;Editor... 的本地化字符串。
        /// </summary>
        internal static string Menu_Script_Script_Editor {
            get {
                return ResourceManager.GetString("Menu_Script_Script_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Sheet 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet {
            get {
                return ResourceManager.GetString("Menu_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filter 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Clear_Filter {
            get {
                return ResourceManager.GetString("Menu_Sheet_Clear_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Filter 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Filter {
            get {
                return ResourceManager.GetString("Menu_Sheet_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Group 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Group {
            get {
                return ResourceManager.GetString("Menu_Sheet_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group &amp;Columns 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Group_Columns {
            get {
                return ResourceManager.GetString("Menu_Sheet_Group_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group &amp;Rows 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Group_Rows {
            get {
                return ResourceManager.GetString("Menu_Sheet_Group_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Insert 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Insert {
            get {
                return ResourceManager.GetString("Menu_Sheet_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Resize... 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Resize {
            get {
                return ResourceManager.GetString("Menu_Sheet_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Settings 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Settings {
            get {
                return ResourceManager.GetString("Menu_Sheet_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ungroup 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Ungroup {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Columns 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Ungroup_All_Columns {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_All_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Rows 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Ungroup_All_Rows {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_All_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Columns 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Ungroup_Selection_Columns {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_Selection_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection Rows 的本地化字符串。
        /// </summary>
        internal static string Menu_Sheet_Ungroup_Selection_Rows {
            get {
                return ResourceManager.GetString("Menu_Sheet_Ungroup_Selection_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Tools 的本地化字符串。
        /// </summary>
        internal static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control &amp;Appearance... 的本地化字符串。
        /// </summary>
        internal static string Menu_Tools_Control_Appearance {
            get {
                return ResourceManager.GetString("Menu_Tools_Control_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Undo 的本地化字符串。
        /// </summary>
        internal static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ungroup 的本地化字符串。
        /// </summary>
        internal static string Menu_Ungroup {
            get {
                return ResourceManager.GetString("Menu_Ungroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ungroup All 的本地化字符串。
        /// </summary>
        internal static string Menu_Ungroup_All {
            get {
                return ResourceManager.GetString("Menu_Ungroup_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Unhide 的本地化字符串。
        /// </summary>
        internal static string Menu_Unhide {
            get {
                return ResourceManager.GetString("Menu_Unhide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;View 的本地化字符串。
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Components 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Components {
            get {
                return ResourceManager.GetString("Menu_View_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Formula Bar 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Components_FormulaBar {
            get {
                return ResourceManager.GetString("Menu_View_Components_FormulaBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Status Bar 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Components_StatusBar {
            get {
                return ResourceManager.GetString("Menu_View_Components_StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Toolbar 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Components_Toolbar {
            get {
                return ResourceManager.GetString("Menu_View_Components_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Freeze To Cell 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Cell {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freeze To &amp;Edges 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Bottom 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Bottom {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom Le&amp;ft 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Bottom_Left {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Bottom_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom Ri&amp;ght 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Bottom_Right {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Bottom_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Left 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Left {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Right {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Top 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Top {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top &amp;Left 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Top_Left {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Top_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top &amp;Right 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Freeze_To_Edges_Top_Right {
            get {
                return ResourceManager.GetString("Menu_View_Freeze_To_Edges_Top_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unfreeze 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Unfreeze {
            get {
                return ResourceManager.GetString("Menu_View_Unfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Visible 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible {
            get {
                return ResourceManager.GetString("Menu_View_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Column Header 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Column_Header {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Column_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Outline &amp;Panel 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Column_Outline_Panel {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Column_Outline_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Frozen Line 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Forzen_Line {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Forzen_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Grid Lines 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Grid_Lines {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Grid_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Horizontal Scrollbar 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Horizontal_ScrollBar {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Horizontal_ScrollBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page &amp;Breaks 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Page_Breaks {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Page_Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Row Header 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Row_Header {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Row_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row &amp;Outline Panel 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Row_Outline_Panel {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Row_Outline_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Sheet Tab 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Sheet_Tab {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Sheet_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Vertical Scrollbar 的本地化字符串。
        /// </summary>
        internal static string Menu_View_Visible_Vertical_ScrollBar {
            get {
                return ResourceManager.GetString("Menu_View_Visible_Vertical_ScrollBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot define named range by specified name. Make sure:
        ///  The name does not begin with a number
        ///  The name does not contain spaces or any invalid characters
        ///  The name is not same as any address of cell and range
        ///  The name is not same as any built-in function names 的本地化字符串。
        /// </summary>
        internal static string Msg_Create_Named_Range_Failed {
            get {
                return ResourceManager.GetString("Msg_Create_Named_Range_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Define named range failed 的本地化字符串。
        /// </summary>
        internal static string Msg_Create_Named_Range_Failed_Title {
            get {
                return ResourceManager.GetString("Msg_Create_Named_Range_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete selected named range? 的本地化字符串。
        /// </summary>
        internal static string Msg_Delete_Named_Range_Confirm {
            get {
                return ResourceManager.GetString("Msg_Delete_Named_Range_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete named range 的本地化字符串。
        /// </summary>
        internal static string Msg_Delete_Named_Range_Confirm_Title {
            get {
                return ResourceManager.GetString("Msg_Delete_Named_Range_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified file cannot be found:  的本地化字符串。
        /// </summary>
        internal static string Msg_File_Not_Found {
            get {
                return ResourceManager.GetString("Msg_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the name of range. 的本地化字符串。
        /// </summary>
        internal static string Msg_Input_Name_Of_Range {
            get {
                return ResourceManager.GetString("Msg_Input_Name_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The address of range is invalid. 的本地化字符串。
        /// </summary>
        internal static string Msg_Invalid_Address_Of_Range {
            get {
                return ResourceManager.GetString("Msg_Invalid_Address_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading file failed:  的本地化字符串。
        /// </summary>
        internal static string Msg_Load_File_Failed {
            get {
                return ResourceManager.GetString("Msg_Load_File_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The document contains macro and executable script. Do you want to run the script now? 的本地化字符串。
        /// </summary>
        internal static string Msg_Load_Script_Prompt {
            get {
                return ResourceManager.GetString("Msg_Load_Script_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable Script 的本地化字符串。
        /// </summary>
        internal static string Msg_Load_Script_Prompt_Title {
            get {
                return ResourceManager.GetString("Msg_Load_Script_Prompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another range with this name has already existed, are you sure to overwrite it? 的本地化字符串。
        /// </summary>
        internal static string Msg_Named_Range_Overwrite {
            get {
                return ResourceManager.GetString("Msg_Named_Range_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No worksheet contained in workbook. 的本地化字符串。
        /// </summary>
        internal static string Msg_No_Current_Worksheet {
            get {
                return ResourceManager.GetString("Msg_No_Current_Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML edit only available when current file format is ReoGrid Format File (.rgf;*.xml). 的本地化字符串。
        /// </summary>
        internal static string Msg_Only_RGF_Edit_XML {
            get {
                return ResourceManager.GetString("Msg_Only_RGF_Edit_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation cannot be performed. 的本地化字符串。
        /// </summary>
        internal static string Msg_Operation_Aborted {
            get {
                return ResourceManager.GetString("Msg_Operation_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another outline has already exists at same position. 的本地化字符串。
        /// </summary>
        internal static string Msg_Outline_Already_Exist {
            get {
                return ResourceManager.GetString("Msg_Outline_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The outline to be added intersects with another one. 的本地化字符串。
        /// </summary>
        internal static string Msg_Outline_Intersected {
            get {
                return ResourceManager.GetString("Msg_Outline_Intersected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No outline found at specified position. 的本地化字符串。
        /// </summary>
        internal static string Msg_Outline_Not_Found {
            get {
                return ResourceManager.GetString("Msg_Outline_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid range to group row or columns. Make sure that the last row or column of worksheet not grouped into any outlines. 的本地化字符串。
        /// </summary>
        internal static string Msg_Outline_Out_Of_Range {
            get {
                return ResourceManager.GetString("Msg_Outline_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level of outlines reached the maximum number of levels (10). 的本地化字符串。
        /// </summary>
        internal static string Msg_Outline_Too_Much {
            get {
                return ResourceManager.GetString("Msg_Outline_Too_Much", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation cannot be performed, range may contains a part of another merged cell. 的本地化字符串。
        /// </summary>
        internal static string Msg_Range_Intersection_Exception {
            get {
                return ResourceManager.GetString("Msg_Range_Intersection_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save changes? 的本地化字符串。
        /// </summary>
        internal static string Msg_Save_Changes {
            get {
                return ResourceManager.GetString("Msg_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor will save current file, continue? 的本地化字符串。
        /// </summary>
        internal static string Msg_Save_File_Immediately {
            get {
                return ResourceManager.GetString("Msg_Save_File_Immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script execution is not supported by this edition. 的本地化字符串。
        /// </summary>
        internal static string Msg_Script_Not_Available {
            get {
                return ResourceManager.GetString("Msg_Script_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 code exported into Clipboard. 的本地化字符串。
        /// </summary>
        internal static string Msg_Source_Code_Exported_Into_Clipboard {
            get {
                return ResourceManager.GetString("Msg_Source_Code_Exported_Into_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Named Range Management 的本地化字符串。
        /// </summary>
        internal static string NamedRangeManage_Caption {
            get {
                return ResourceManager.GetString("NamedRangeManage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Named ranges: 的本地化字符串。
        /// </summary>
        internal static string NamedRangeManage_Named_Ranges {
            get {
                return ResourceManager.GetString("NamedRangeManage_Named_Ranges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New... 的本地化字符串。
        /// </summary>
        internal static string NamedRangeManage_New {
            get {
                return ResourceManager.GetString("NamedRangeManage_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Color 的本地化字符串。
        /// </summary>
        internal static string NoColor {
            get {
                return ResourceManager.GetString("NoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number 的本地化字符串。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paging Order 的本地化字符串。
        /// </summary>
        internal static string Paging_Order {
            get {
                return ResourceManager.GetString("Paging_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper 的本地化字符串。
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentage 的本地化字符串。
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pixel 的本地化字符串。
        /// </summary>
        internal static string Pixel {
            get {
                return ResourceManager.GetString("Pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portrait 的本地化字符串。
        /// </summary>
        internal static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adjust_To 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Adjust_To {
            get {
                return ResourceManager.GetString("PrintSettings_Adjust_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Settings 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Caption {
            get {
                return ResourceManager.GetString("PrintSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down, then over 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Down_Then_Over {
            get {
                return ResourceManager.GetString("PrintSettings_Down_Then_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orientation: 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Orientation {
            get {
                return ResourceManager.GetString("PrintSettings_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Over, then down 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Over_Then_Down {
            get {
                return ResourceManager.GetString("PrintSettings_Over_Then_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paper Size: 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Paper_Size {
            get {
                return ResourceManager.GetString("PrintSettings_Paper_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % normal size 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Percent_Normal_Size {
            get {
                return ResourceManager.GetString("PrintSettings_Percent_Normal_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Setup 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Setup {
            get {
                return ResourceManager.GetString("PrintSettings_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show &amp;Grid Lines 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Show_Grid_Lines {
            get {
                return ResourceManager.GetString("PrintSettings_Show_Grid_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show &amp;Margins 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Show_Margins {
            get {
                return ResourceManager.GetString("PrintSettings_Show_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visible Settings 的本地化字符串。
        /// </summary>
        internal static string PrintSettings_Visible_Settings {
            get {
                return ResourceManager.GetString("PrintSettings_Visible_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protection 的本地化字符串。
        /// </summary>
        internal static string Protection {
            get {
                return ResourceManager.GetString("Protection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locked (Read-only) 的本地化字符串。
        /// </summary>
        internal static string ProtectionPage_Locked {
            get {
                return ResourceManager.GetString("ProtectionPage_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize worksheet 的本地化字符串。
        /// </summary>
        internal static string Resize_Caption {
            get {
                return ResourceManager.GetString("Resize_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Columns: 的本地化字符串。
        /// </summary>
        internal static string Resize_Columns {
            get {
                return ResourceManager.GetString("Resize_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (max: 32,768) 的本地化字符串。
        /// </summary>
        internal static string Resize_Columns_Remark {
            get {
                return ResourceManager.GetString("Resize_Columns_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Rows: 的本地化字符串。
        /// </summary>
        internal static string Resize_Rows {
            get {
                return ResourceManager.GetString("Resize_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (max: 1,048,576) 的本地化字符串。
        /// </summary>
        internal static string Resize_Rows_Remark {
            get {
                return ResourceManager.GetString("Resize_Rows_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row 的本地化字符串。
        /// </summary>
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Script Function 的本地化字符串。
        /// </summary>
        internal static string RunFunction_Caption {
            get {
                return ResourceManager.GetString("RunFunction_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close this window after running 的本地化字符串。
        /// </summary>
        internal static string RunFunction_Close_This_Window_After_Running {
            get {
                return ResourceManager.GetString("RunFunction_Close_This_Window_After_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Functions: 的本地化字符串。
        /// </summary>
        internal static string RunFunction_Functions {
            get {
                return ResourceManager.GetString("RunFunction_Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Run 的本地化字符串。
        /// </summary>
        internal static string RunFunction_Run {
            get {
                return ResourceManager.GetString("RunFunction_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample 的本地化字符串。
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scaling 的本地化字符串。
        /// </summary>
        internal static string Scaling {
            get {
                return ResourceManager.GetString("Scaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column width 的本地化字符串。
        /// </summary>
        internal static string SetHeaderSize_Caption_Column {
            get {
                return ResourceManager.GetString("SetHeaderSize_Caption_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row height 的本地化字符串。
        /// </summary>
        internal static string SetHeaderSize_Caption_Row {
            get {
                return ResourceManager.GetString("SetHeaderSize_Caption_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solid 的本地化字符串。
        /// </summary>
        internal static string SolidColor {
            get {
                return ResourceManager.GetString("SolidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        internal static string Vertical_Alignment_Bottom {
            get {
                return ResourceManager.GetString("Vertical_Alignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string Vertical_Alignment_General {
            get {
                return ResourceManager.GetString("Vertical_Alignment_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Middle 的本地化字符串。
        /// </summary>
        internal static string Vertical_Alignment_Middle {
            get {
                return ResourceManager.GetString("Vertical_Alignment_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        internal static string Vertical_Alignment_Top {
            get {
                return ResourceManager.GetString("Vertical_Alignment_Top", resourceCulture);
            }
        }
    }
}
